# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2


# Set the version of Python and other tools you might need
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

    commands:
        - pip install -U 'setuptools>=61.0'
        - python -m pip install -U pip
        - pip install -r requirements.txt
        - pip install -e .
        - pip install -r docs/requirements.txt
        - pip list
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - mkdir -p docs/api
        - sphinx-apidoc -o docs/api sbucket
        - cp docs/api/* docs
        - rm -rf docs/api
        - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html/

