name: CI/CD Pipeline

on: [ push, pull_request, workflow_dispatch ]

env:
  HOME_REPO: thebjorn/smart-bucket

jobs:
  ci-lint:
    name: CI:Lint
    runs-on: ubuntu-latest
    env:
      LINTDIR: ./ghlint
    steps:
      # setup environment
      - uses: actions/checkout@v3
      - name: setup directories
        shell: bash
        run: |
          mkdir -p $LINTDIR
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install flake8
      - run: flake8 sbucket/** --max-line-length=199

  ci-test:
    name: CI:Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
        python-version: [ '3.11' ]
        os: [ubuntu-latest]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      S3_TEST_BUCKET_NAME: ${{ secrets.S3_TEST_BUCKET_NAME }}

    steps:
      # setup environment
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - run: pip install -r requirements.txt
      - run: pip install -r requirements-tests.txt
      - run: pip install -e .
      - run: pip list
      - run: pytest -vv --cov=sbucket tests

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false

  cd:
    name: CD
    needs: ci-test
    runs-on: ubuntu-latest
    steps:
      # setup environment
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Cleanup
        run: |
          rm -rf dist
          rm -rf build

      - run: pip install -U build twine
      - run: python -m build

      - name: Upload packages as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: dist/

      # - name: Build docs
      #   run: python setup.py build_sphinx

      # - name: Upload docs as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Docs
      #     path: build/sphinx/html/

      - name: Deploy to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == env.HOME_REPO
        shell: bash
        run: |
          twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*      

      - name: Create Github release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == env.HOME_REPO
        with:
          artifacts: "dist/*"
          owner: thebjorn
          repo: smart-bucket
          token: ${{ secrets.GITHUB_TOKEN }}
